server/.gitignore
Detail
======
- Add gitignore for django project
=> Backend: Add gitignore

server/api/admin.py, server/api/apps.py, server/api/models.py, server/api/tests.py, server/api/urls.py, server/api/views.py, server/requirements.txt, server/server/settings.py, server/server/urls.py
Detail
======
- djangorestframework, drf-yasg 추가
- 테스트 API 작성
=> Backend: 프로젝트 뼈대 작성

server/README.md
=> Backend: README 추가

server/.dockerignore, server/Dockerfile
Detail
======
- Dockerfile 추가
- .dockerignore에 venv 추가
=> Backend: Dockerfile 추가

server/Dockerfile, server/init, server/server/settings.py
Detail
======
- Dockerfile 수정
- secrets.json init스크립트 추가
- settings.py에 허용된 도메인 추가
=> Backend: GCP VM에 맞는 스크립트 추가

server/Dockerfile, server/server/settings.py
Detail
======
- Dockerfile에 오라클 라이브러리 추가
=> Backend: Dockerfile에 오라클 라이브러리 추가

server/api/model/models.py, server/server/settings.py
Detail
======
- Add models
- auto generated by inspectdb
=> Backend: Add models

server/api/serializers.py, server/api/urls.py, server/api/views.py
Detail
======
- Add auth/login API
=> Backend: Add auth/login API

server/api/urls.py, server/api/views.py, server/requirements.txt, server/server/settings.py
Detail
======
- Add jwt token
- created in signin/signup
=> Backend: Add jwt token

docs/api_definition.md, server/api/serializers.py, server/api/urls.py, server/api/views.py
Detail
======
- 영화 생성 API 추가
- 관리자만 생성 가능
- 로그아웃 API 추가
- API 스키마 일부 변경
=> Backend: 영화 생성 API 추가

docs/api_definition.md, server/api/urls.py, server/api/views.py
Detail
======
- JWT가 없는 경우 401 Unauthorized
- API 정의서 수정
- trailing slash 제거
=> Hotfix: JWT가 없는 경우 401 반환

docs/api_definition.md, server/api/model/models.py, server/api/serializers.py, server/api/views.py
Detail
======
- GET /movies/{movie_id} 추가
- Movie.movie_time 필드 TimeField로 변경
=> Backend: GET /movies/{movie_id} 추가

docs/api_definition.md
Detail
======
- /movies GET 응답 수정
=> Doc: /movies GET 응답 수정

server/api/views.py, server/core/user.py
Detail
======
- 로그인/관리자 여부 확인 함수 모듈화
- UsrViewSet을 ModelViewSet에서 ViewSet으로 변경
=> Backend: 로그인/관리자 여부 확인 함수 모듈화

server/api/serializers.py, server/api/urls.py, server/api/views.py
Detail
======
- 포인트 조회, 비밀번호 변경 API 추가
- /user/point GET
- /user/password POST
- {"password": "현재비밀번호", "newPassword": "새비밀번호"}
=> Backend: 포인트 조회, 비밀번호 변경 API 추가

server/server/secrets.json.~, server/server/settings.py
Detail
======
- secrets.json 교체
=> Backend: secrets.json 교체

server/server/settings.py
Detail
======
- Change Timezone UTC to KST
=> Backend: Change Timezone

docs/api_definition.md, server/api/serializers.py, server/api/views.py
Detail
======
- /user/profile 추가
- /auth 하위 API들에서 tickets 제거
=> Backend: /user/profile 추가

server/api/serializers.py, server/api/urls.py, server/api/views.py
Detail
======
- Add show create API
- showStartTime: "YYYY-MM-DD hh:mm:ss"
- KST 기준
=> Backend: Add show create API

docs/api_definition.md, server/api/serializers.py, server/api/views.py
Detail
======
- /movies GET 추가
- /auth/{login, signup}에서 response body 제거
=> Backend: /movies GET 추가

server/api/views.py
Detail
======
- 영화 삭제 시 상영정보가 존재하면 삭제되지 않도록 변경
=> Backend: /movies/<id> DELETE 수정

docs/api_definition.md, server/api/serializers.py, server/api/views.py
Detail
======
- 상영일정 조회 API 추가
- seatsInfo는 미구현
- movie_id가 없을 시 400
- 해당 영화가 없을 시 404
- 상영정보가 없을 때에는 빈 배열
=> Backend: 상영일정 조회 API 추가

docs/api_definition.md, server/api/model/models.py, server/api/serializers.py, server/api/urls.py, server/api/views.py
Detail
======
- bookingCount, 예매한 좌석 미구현
=> Backend: 상영일정 자리 조회 API 추가

server/api/serializers.py, server/api/views.py
Detail
======
- ticketAmount, seatIds 받게 변경
=> Backend: 예매 API 스키마 변경

docs/api_definition.md, server/api/serializers.py, server/api/views.py
Detail
======
- 회원 전용
- count API 구현x
=> Backend: 티켓 조회 API 추가

docs/api_definition.md, server/api/views.py
=> Backend: 보유한 티켓 개수 API 추가

server/api/urls.py, server/api/views.py, server/core/pay.py
Detail
======
- 예매 취소 API 추가
- 회원 전용
=> Backend: 예매 취소 API 추가

Dockerfile, frontend/.gitignore, nginx/default.conf, server/.gitignore, server/server/settings.py, server/server/urls.py
Detail
======
- 리액트 도커파일 추가
- SSL 설정
- 장고 staticfile 설정
=> Deploy: nginx 설정

server/api/views.py, server/core/pay.py
Detail
======
- USR테이블에 비회원 계정 추가
- 추가한 비회원 계정으로 예매
- 비회원은 포인트 예매 불가능
=> Backend: 비회원 예매 추가

server/api/views.py
Detail
======
- 비회원 티켓 조회 API 추가
=> Backend: 비회원 티켓 조회 API 추가

docs/api_definition.md
Detail
======
- 비회원 티켓 조회 API 응답에서 email 제거
=> doc: update /user/profile?email={email}, /user/tickets?email={email}

server/api/views.py
Detail
======
- API 호출시각 이후에 상영하는 정보만 받아오게 수정
=> Backend: /shows/<id> 날짜 필터 추가

server/api/serializers.py, server/api/views.py
Detail
======
- 좌석 조회 응답에 포스터 URL 추가
- 필요없는 주석 제거
=> Backend: 좌석 조회 응답에 포스터 URL 추가

server/api/views.py
Detail
======
- 취소한 티켓 개수는 카운트되지 않게 수정
=> Backend: /shows에서 남은 자리 개수 오류 수정

server/Dockerfile, server/server/settings.py
Detail
======
- DJANGO_LOG_LEVEL=DEBUG시 로그 출력
=> Backend: 데이터베이스 로깅

frontend/nginx/default.conf, server/server/settings.py
Detail
======
- 스웨거 HTTPS상에서도 동작하게 변경
=> Backend: 스웨거 HTTPS상에서도 동작하게 변경

docs/api_definition.md, server/api/serializers.py, server/api/views.py
Detail
======
- 상영정보 조회 API에 종료시간 추가
=> Backend: 상영정보 조회 API에 종료시간 추가

server/api/serializers.py
Detail
======
- 문자열 길이가 아니라 바이트 수만큼 max_length 설정
- Fix #75
=> Backend: 유니코드 max_length 문제 수정

server/api/serializers.py, server/api/views.py
Detail
======
- /movies/{id} PATCH
=> Backend: 영화 수정 API 추가

frontend/nginx/default.conf, server/api/model/admin.py
Detail
======
- 장고 어드민페이지에 모델 등록
=> Backend: 장고 어드민페이지 추가

server/api/views.py
Detail
======
- 쿼리 실행시 SHOW_START_TIME으로 정렬 후 그룹핑
=> Backend: 상영정보 조회시 날짜별 그룹핑함수 수정

server/api/model/admin.py, server/api/model/models.py
Detail
======
- 어드민 페이지에 코드데이터 추가
=> Backend: 어드민 페이지에 코드데이터 추가

server/api/model/admin.py, server/api/views.py
Detail
======
- /movies GET 개봉일 순으로 정렬
=> Backend: 영화 개봉일 순으로 정렬

server/api/views.py
Detail
======
- 트랜잭션 수정
- 주석 수정
=> Backend: 트랜잭션, 주석 수정

server/api/views.py
Detail
======
- 영화에 상영시간 정보가 없을 시 400 리턴
=> Backend: 러닝타임 없는 영화 상영정보 등록 시 예외처리

server/api/views.py
=> Backend: 영화 시간, 등급 수정 오류 수정

server/api/views.py
Detail
======
- TICKET.TICKET_STATE는 이미 NOT NULL이기 때문에 NULL 검사 하지 않음
=> Backend: 좌석 정보 서브쿼리 수정

server/api/model/models.py
Detail
======
- Date -> DateTime
=> Backend: Pay.pay_date DateTime으로 변경
